#!/bin/bash

device_id () {
    DEVICE=$1; shift
    echo $@ | awk '{print $8}' | \
	    if [[ "$@" = "" ]]; \
		then echo $DEVICE; \
	    else echo $@; \
	    fi;
}

active_monitor () {
  if [[ -z "$(connected-DVI-monitors)" ]]; \
  then echo $(connected-primary-monitor); \
  else echo $(connected-DVI-monitors); \
  fi
}

STYLUS=$( device_id "stylus" "$( xsetwacom --list devices | \
	awk '$0 ~ /stylus/ {print $8}')" )
PAD=$( device_id 'pad' $( xsetwacom --list devices | \
	awk '$0 ~ /pad/ {print $8}') )
ERASER=$( device_id 'eraser' $( xsetwacom --list devices | \
	awk '$0 ~ /eraser/ {print $8}') )
CURSOR=$( device_id 'cursor' $( xsetwacom --list devices | \
	awk '$0 ~ /cursor/ {print $8}') )
MONITOR=$( active_monitor )

#STYLUS="Wacom Intuos BT S Pen stylus"
#PAD="Wacom Intuos BT S Pad pad"
#ERASER="Wacom Intuos BT S Pen eraser"
#CURSOR="Wacom Intuos BT S Pen cursor"
#MONITOR="DVI-I-1-1"

#xrandr --output DVI-I-1-1 --rotate left
#xrandr --output DVI-I-1-1 --right-of eDP-1
#xrandr --output DVI-I-1-1 --pos 1920x0
#xrandr --output DVI-I-1-1 --pos 1920x-740

# Run default Wacom settings

init-wacom

# Map devices to output

xsetwacom --set $STYLUS MapToOutput $MONITOR
xsetwacom --set $PAD MapToOutput $MONITOR
xsetwacom --set $ERASER MapToOutput $MONITOR
xsetwacom --set $CURSOR MapToOutput $MONITOR

# Rotate pad counterclockwise 90°

xsetwacom --set $STYLUS rotate cw
xsetwacom --set $PAD rotate cw
xsetwacom --set $ERASER rotate cw
xsetwacom --set $CURSOR rotate cw
