#!/bin/bash

DEV=$1

# Insert your aliases and mac-addresses here
BUDS='1C:E6:1D:C5:A0:02'
JBL='88:D0:39:2D:42:F5'

# Route aliases to bluetoothctl
bluetoothctl power on && \
if [[ -n "$DEV" ]]; then
    if [[ "$DEV" = "JBL" ]]; then
        bluetoothctl connect $JBL
    elif [[ "$DEV" = "BUDS" ]]; then
        bluetoothctl connect $BUDS
    fi
else
    echo "No device specified!"
fi
