#!/bin/bash

KEY='n1c3h4ndwr1t1n9'
LOC='/usr/local/bin/.wifi_auth'

function decrypt () {
    echo "$(cat $1 | openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000 -salt -pass pass:$2)"
}

nmcli con delete eduroam;
nmcli con add \
    type wifi \
    con-name "eduroam" \
    ifname "wlp2s0" \
    ssid "eduroam" \
    wifi-sec.key-mgmt "wpa-eap" \
    802-1x.identity "eythore19@ru.is" \
    #802-1x.password "$( decrypt $LOC $KEY )" \
    802-1x.password "Kassi110" \
    802-1x.system-ca-certs "yes" \
    802-1x.ca-path "~/.cat_installer/ca.pem" \
    802-1x.domain-suffix-match "itu.dk" \
    802-1x.eap "peap" \
    802-1x.phase2-auth "mschapv2" 

nmcli con up eduroam
