#!/bin/bash

occurrencenum=$(pacmd list-sinks | grep 'index' | grep -n '* index' | awk -F ':' '{print $1}')
pacmd list-cards | grep 'device.description' | sed "${occurrencenum}q;d" | awk -F ' = ' '{print $NF}' | sed 's/"//g'

